export const AdminCourses = [
  {
    courseImg: "/teacher1.png",
    courseName: "Graphics Design",
    category: "4 SubCategories",
    description: "Website design and develop the website with web applications",
    photoshop: "Photoshop",
    adobe: "Adobe Illustration",
    design: "Logo Design",
    drawing: "Drawing",
    figma: "Figma",
  },
  {
    courseImg: "/teacher1.png",
    courseName: "Graphics Design",
    category: "4 SubCategories",
    description: "Website design and develop the website with web applications",
    photoshop: "Photoshop",
    adobe: "Adobe Illustration",
    design: "Logo Design",
    drawing: "Drawing",
    figma: "Figma",
  },
  {
    courseImg: "/teacher1.png",
    courseName: "Graphics Design",
    category: "4 SubCategories",
    description: "Website design and develop the website with web applications",
    photoshop: "Photoshop",
    adobe: "Adobe Illustration",
    design: "Logo Design",
    drawing: "Drawing",
    figma: "Figma",
  },
  {
    courseImg: "/teacher1.png",
    courseName: "Graphics Design",
    category: "4 SubCategories",
    description: "Website design and develop the website with web applications",
    photoshop: "Photoshop",
    adobe: "Adobe Illustration",
    design: "Logo Design",
    drawing: "Drawing",
    figma: "Figma",
  },
  {
    courseImg: "/teacher1.png",
    courseName: "Graphics Design",
    category: "4 SubCategories",
    description: "Website design and develop the website with web applications",
    photoshop: "Photoshop",
    adobe: "Adobe Illustration",
    design: "Logo Design",
    drawing: "Drawing",
    figma: "Figma",
  },
  {
    courseImg: "/teacher1.png",
    courseName: "Graphics Design",
    category: "4 SubCategories",
    description: "Website design and develop the website with web applications",
    photoshop: "Photoshop",
    adobe: "Adobe Illustration",
    design: "Logo Design",
    drawing: "Drawing",
    figma: "Figma",
  },

  {
    courseImg: "/teacher1.png",
    courseName: "Graphics Design",
    category: "4 SubCategories",
    description: "Website design and develop the website with web applications",
    photoshop: "Photoshop",
    adobe: "Adobe Illustration",
    design: "Logo Design",
    drawing: "Drawing",
    figma: "Figma",
  },
  {
    courseImg: "/teacher1.png",
    courseName: "Graphics Design",
    category: "4 SubCategories",
    description: "Website design and develop the website with web applications",
    photoshop: "Photoshop",
    adobe: "Adobe Illustration",
    design: "Logo Design",
    drawing: "Drawing",
    figma: "Figma",
  },
];
