export const AdminCourses = [
  {
    id: "admin-1",
    courseBanner: "/course-3.png",
    coursePreview: "/coursePreview.mp4",
    courseVideo: "/courseVideo.mp4",
    teacher: "SchooledAfrika",
    title: "Introduction to Mathematics",
    description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    price: "$300",
  },
  {
    id: "admin-2",
    courseBanner: "/course-4.png",
    coursePreview: "/coursePreview.mp4",
    courseVideo: "/courseVideo.mp4",
    teacher: "SchooledAfrika",
    title: "Introduction to Government",
    description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    price: "$200",
  },
  {
    id: "admin-3",
    courseBanner: "/course-5.png",
    coursePreview: "/coursePreview.mp4",
    courseVideo: "/courseVideo.mp4",
    teacher: "SchooledAfrika",
    title: "Introduction to Biology",
    description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    price: "$3400",
  },
  {
    id: "admin-4",
    courseBanner: "/course-4.png",
    coursePreview: "/coursePreview.mp4",
    courseVideo: "/courseVideo.mp4",
    teacher: "Maurice Odo",
    title: "Further Mathematics",
    description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    price: "$300",
  },
  {
    id: "admin-5",
    courseBanner: "/course-5.png",
    coursePreview: "/coursePreview.mp4",
    courseVideo: "/courseVideo.mp4",
    teacher: "Austine David",
    title: "Introduction to Technology",
    description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    price: "$300",
  },
  {
    id: "admin-6",
    courseBanner: "/course-3.png",
    coursePreview: "/coursePreview.mp4",
    courseVideo: "/courseVideo.mp4",
    teacher: "Sarah Adebayor",
    title: "Introduction to English",
    description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    price: "$300",
  },

 
  
];
