export const JobList = [
  {
    subject: "Economics",
    grade: "Grade 10",
    location: "Lagos",
    jobType: "Full-Time",
    amount: "$80,000 - $120,000",
    nameOfViews: "Views",
    numberOfViews: "5",
    nameOfApplicants: "Applicants",
    numberOfApplicants: "2",
    edit: "Edit Listing",
    viewApplicants: "View Applicants",
  },
  {
    subject: "Economics",
    grade: "Grade 10",
    location: "Lagos",
    jobType: "Full-Time",
    amount: "$80,000 - $120,000",
    nameOfViews: "Views",
    numberOfViews: "5",
    nameOfApplicants: "Applicants",
    numberOfApplicants: "2",
    edit: "Edit Listing",
    viewApplicants: "View Applicants",
  },
  {
    subject: "Economics",
    grade: "Grade 10",
    location: "Lagos",
    jobType: "Full-Time",
    amount: "$80,000 - $120,000",
    nameOfViews: "Views",
    numberOfViews: "5",
    nameOfApplicants: "Applicants",
    numberOfApplicants: "2",
    edit: "Edit Listing",
    viewApplicants: "View Applicants",
  },
  {
    subject: "Economics",
    grade: "Grade 10",
    location: "Lagos",
    jobType: "Full-Time",
    amount: "$80,000 - $120,000",
    nameOfViews: "Views",
    numberOfViews: "5",
    nameOfApplicants: "Applicants",
    numberOfApplicants: "2",
    edit: "Edit Listing",
    viewApplicants: "View Applicants",
  },
  {
    subject: "Economics",
    grade: "Grade 10",
    location: "Lagos",
    jobType: "Full-Time",
    amount: "$80,000 - $120,000",
    nameOfViews: "Views",
    numberOfViews: "5",
    nameOfApplicants: "Applicants",
    numberOfApplicants: "2",
    edit: "Edit Listing",
    viewApplicants: "View Applicants",
  },
];
