export const offers = [
    {
      id: "offer-1",
      icon: "/maths.png",
      institution: "Brilliant schools",
      title: "Mathematics teacher",
      grade: "Grade 12",
      type: "Hybrid",
      location: "Lagos",
    },
    {
      id: "offer-2",
      icon: "/english.png",
      institution: "Alpha schools",
      title: "English teacher",
      grade: "Grade 1",
      type: "Hybrid",
      location: "Enugu",
    },
    {
      id: "offer-3",
      icon: "/chem.png",
      institution: "Beta schools",
      title: "Chemistry teacher",
      grade: "Grade 11",
      type: "Hybrid/Remote",
      location: "Calabar",
    },
    {
      id: "offer-4",
      icon: "/fmass.png",
      institution: "Gamma schools",
      title: "Further Mathematics teacher",
      grade: "Grade 9",
      type: "Hybrid",
      location: "Lokoja",
    },
    {
      id: "offer-5",
      icon: "/lit.png",
      institution: "Lambda schools",
      title: "Literature teacher",
      grade: "Grade 5",
      type: "Hybrid",
      location: "Ibadan",
    },
    {
      id: "offer-6",
      icon: "/agric.png",
      institution: "XI schools",
      title: "Agriculture teacher",
      grade: "Grade 3",
      type: "Hybrid/Remote",
      location: "Awka",
    },
    {
      id: "offer-7",
      icon: "/bio.png",
      institution: "Apex schools",
      title: "Biology teacher",
      grade: "Grade 10",
      type: "Hybrid",
      location: "Zamfara",
    },
    {
      id: "subject-8",
      icon: "/account.png",
      institution: "Binary Brains schools",
      title: "Accounting teacher",
      grade: "Grade 8",
      type: "Hybrid",
      location: "Benin",
    },
   
  ];
  