export const OneOnOneList = [
  {
    teacherImg: "/teacher1.png",
    teacherName: "Alex Iwobi Samuel",
    active: "Active",
    calIcon: "/svgs/calculate.svg",
    subject: "Mathematics",
    grade: "Grade 11",
    classType: "Lesson",
    clockIcon: "/svgs/clock.svg",
    duration: "Duration : 2 Hours",
    time: "Class Starts : 10:00AM",
    viewDetails: "View Details",
    sessionsIcon: "/svgs/session.svg",
    startSession: "Start Session",
  },
  {
    teacherImg: "/teacher2.png",
    teacherName: "Grace Elisa",
    active: "Active",
    calIcon: "/svgs/calculate.svg",
    subject: "Mathematics",
    grade: "Grade 11",
    classType: "Homework Support",
    clockIcon: "/svgs/clock.svg",
    duration: "Duration : 2 Hours",
    time: "Class Starts : 10:00AM",
    viewDetails: "View Details",
    sessionsIcon: "/svgs/session.svg",
    startSession: "Start Session",
  },
  {
    teacherImg: "/teacher3.png",
    teacherName: "Tyrese Maxi",
    active: "Active",
    calIcon: "/svgs/calculate.svg",
    subject: "Mathematics",
    grade: "Grade 11",
    classType: "Lesson",
    clockIcon: "/svgs/clock.svg",
    duration: "Duration : 2 Hours",
    time: "Class Starts : 10:00AM",
    viewDetails: "View Details",
    sessionsIcon: "/svgs/session.svg",
    startSession: "Start Session",
  },
  {
    teacherImg: "/teacher4.png",
    teacherName: "Irina Smith",
    active: "Active",
    calIcon: "/svgs/calculate.svg",
    subject: "Mathematics",
    grade: "Grade 11",
    classType: "Lesson",
    clockIcon: "/svgs/clock.svg",
    duration: "Duration : 2 Hours",
    time: "Class Starts : 10:00AM",
    viewDetails: "View Details",
    sessionsIcon: "/svgs/session.svg",
    startSession: "Start Session",
  },
];
