export const ParentCoursesData = [
  {
    id: "course-1",
    icon: "/module-1.png",
    classes: "Grade 11",
    title: "Mathematics Waec Prep",
    time: "125 Minutes",
    module: "12 Modules",
    pricing: "$33.00",
    purchase: "Purchase Course",
    payment: "Paid",
  },
  {
    id: "course-2",
    icon: "/module-2.png",
    classes: "Grade 11",
    title: "English Neco Prep",
    time: "125 Minutes",
    module: "12 Modules",
    pricing: "$33.00",
    purchase: "Purchase Course",
  },
  {
    id: "course-2",
    icon: "/module-2.png",
    classes: "Grade 11",
    title: "English Neco Prep",
    time: "125 Minutes",
    module: "12 Modules",
    pricing: "$33.00",
    purchase: "Purchase Course",
  },
  {
    id: "course-2",
    icon: "/module-2.png",
    classes: "Grade 11",
    title: "English Neco Prep",
    time: "125 Minutes",
    module: "12 Modules",
    pricing: "$33.00",
    purchase: "Purchase Course",
  },
  {
    id: "course-2",
    icon: "/module-2.png",
    classes: "Grade 11",
    title: "English Neco Prep",
    time: "125 Minutes",
    module: "12 Modules",
    pricing: "$33.00",
    purchase: "Purchase Course",
  },
  {
    id: "course-2",
    icon: "/module-2.png",
    classes: "Grade 11",
    title: "English Neco Prep",
    time: "125 Minutes",
    module: "12 Modules",
    pricing: "$33.00",
    purchase: "Purchase Course",
  },
];
