export const sessions = [
    {
      id: "session-1",
      icon: "/noavatar.png",
      subject: "Mathematics",
      name: "Maurice Odo",
      country: "Nigeria",
      email: "odomaurice@gmail.com",
      gender: "Male",
      grade: "Grade 4",
      sessionType: "Homework Support",
      time: "2PM",
      hours: "2 hours",
      length: "2 months",
      days: "Mon, Tue, Thurs",
      type: "Hybrid",
      location: "Lagos",
    },
    {
      id: "session-2",
      icon: "/noavatar.png",
      subject: "English",
      name: "David Augustine",
      country: "Spain",
      email: "david@gmail.com",
      gender: "Male",
      grade: "Grade 6",
      sessionType: "1 on 1 session",
      time: "12PM",
      hours: "2 hours",
      length: "3 months",
      days: "Mon, Fri",
      type: "Remote",
      location: "Enugu",
    },
    {
      id: "session-3",
      icon: "/noavatar.png",
      subject: "Chemistry",
      name: "Beatrice Igho",
      country: "U.S.A",
      email: "beatrice@gmail.com",
      gender: "Female",
      grade: "Grade 10",
      sessionType: "Homework Support",
      time: "2PM",
      hours: "2 hours",
      length: "2 months",
      days: "Wed, Thurs",
      type: "On-site",
      location: "Calabar",
    },
    {
      id: "session-4",
      icon: "/noavatar.png",
      subject: "Further Mathematics",
      name: "Ekene Umibe",
      country: "Nigeria",
      email: "ekene@gmail.com",
      gender: "Female",
      grade: "Grade 10",
      sessionType: "1 on 1 session",
      time: "3PM",
      hours: "2 hours",
      length: "1 months",
      days: "Friday",
      type: "Hybrid",
      location: "Portharcourt",
    },
    {
      id: "session-5",
      icon: "/noavatar.png",
      subject: "Government",
      name: "Oluwale Christopher",
      country: "Nigeria",
      email: "oluwale@gmail.com",
      gender: "Male",
      grade: "Grade 11",
      sessionType: "Homework Support",
      time: "6PM",
      hours: "2 hours",
      length: "1 month",
      days: "Mon, Tue, Thurs",
      type: "Hybrid",
      location: "Lagos",
    },
    {
      id: "session-6",
      icon: "/noavatar.png",
      subject: "Agriculture",
      name: "Maurice Odo",
      country: "Nigeria",
      email: "odomaurice@gmail.com",
      gender: "Male",
      grade: "Grade 4",
      sessionType: "Homework Support",
      time: "2PM",
      hours: "2 hours",
      length: "2 months",
      days: "Mon, Tue, Thurs",
      type: "Hybrid",
      location: "Awka",
    },
    
  ];
  