export const StudentCourseVideoData = [
  {
    numbering: 1,
    module: "Module 1",
    title: "Quadratic Equations",
  },
  {
    numbering: 2,
    module: "Module 2",
    title: "Introduction to Calculus",
  },
  {
    numbering: 3,
    module: "Module 3",
    title: "Trigonometry",
  },
  {
    numbering: 4,
    module: "Module 4",
    title: "Longitude & Latitude",
  },
  {
    numbering: 5,
    module: "Module 5",
    title: "Arithmetic Progression",
  },
  {
    numbering: 6,
    module: "Module 6",
    title: "Technical Drawing & Construction",
  },
];

export const StudentCoursesData = [
  {
    id: "course-1",
    icon: "/module-1.png",
    classes: "Grade 11",
    title: "Mathematics Waec Prep",
    time: "125 Minutes",
    module: "12 Modules",
    pricing: "$33.00",
    purchase: "Purchase Course",
    payment: "Paid",
  },
  {
    id: "course-2",
    icon: "/module-2.png",
    classes: "Grade 11",
    title: "English Neco Prep",
    time: "125 Minutes",
    module: "12 Modules",
    pricing: "$33.00",
    purchase: "Purchase Course",
  },
  {
    id: "course-2",
    icon: "/module-2.png",
    classes: "Grade 11",
    title: "English Neco Prep",
    time: "125 Minutes",
    module: "12 Modules",
    pricing: "$33.00",
    purchase: "Purchase Course",
  },
  {
    id: "course-2",
    icon: "/module-2.png",
    classes: "Grade 11",
    title: "English Neco Prep",
    time: "125 Minutes",
    module: "12 Modules",
    pricing: "$33.00",
    purchase: "Purchase Course",
  },
  {
    id: "course-2",
    icon: "/module-2.png",
    classes: "Grade 11",
    title: "English Neco Prep",
    time: "125 Minutes",
    module: "12 Modules",
    pricing: "$33.00",
    purchase: "Purchase Course",
  },
  {
    id: "course-2",
    icon: "/module-2.png",
    classes: "Grade 11",
    title: "English Neco Prep",
    time: "125 Minutes",
    module: "12 Modules",
    pricing: "$33.00",
    purchase: "Purchase Course",
  },
];
